#spring.application.name=RegisterLogin

server:
  port: 8088
  servlet:
    context-path: /fja-fap
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "CDHqPBzvf/cd16lcRMOGzLh3d0jFYam6J+cSO1luuzHgl/4KcutQLJes88De76A5"
